---
# https://backstage.io/docs/features/software-catalog/descriptor-format/#kind-domain
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: vespa-clusters
  description: Vespa clusters
  title: Vespa Cluster
spec:
  owner: guests

---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: vespa-clusters
  description: Vespa Clusters
spec:
  owner: guests

---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vespa-cluster1
  description: Vespa cluster in several regions
  label:
    - vespa-plugin/regions: "eu-west1,eu-east2,us-central1"
    - vespa-plugin/endpoint: "srv:_vespa-cluster1-config._http.services.{region}.my-domain.net"
    - vespa-plugin/query-endpoint: "srv:_vespa-cluster1-query._http.services.{region}.my-domain.net"
  tags:
    - vespa
spec:
  type: service
  lifecycle: experimental
  owner: guests
  domain: vespa-clusters
  system: vespa-clusters


---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: vespa-cluster2-us-central1
  description: Vespa cluster in a single region
  label:
    - vespa-plugin/regions: "us-central1"
    - vespa-plugin/endpoint: "http://vespa-cluster2-config.us-central1.my-domain.net.:19071"
    - vespa-plugin/query-endpoint: "http://vespa-cluster2-query.us-central1.my-domain.net.:8080"
  tags:
    - vespa
spec:
  type: service
  lifecycle: experimental
  owner: guests
  domain: vespa-clusters
  system: vespa-clusters


